---
- name: install prerequirements
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
    update_cache: true
  tags: install
- name: add repository key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install
- name: add mongodb repo
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    state: present
  tags: install
- name: install mongodb
  apt:
    name: mongodb-org
    update_cache: true
  tags: install
- name: enabling mongod service
  systemd:
    name: mongod
    state: started
    enabled: true
  tags: install
