---
- name: Deploy App
  hosts: app

  tasks:
    - name: Fetch the latest verison of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/{{ ansible_user }}/reddit'
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: '/home/{{ ansible_user }}/reddit'

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
